/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThoughtLeadershipRouteImport } from './routes/thought-leadership'
import { Route as StaticSocialRouteImport } from './routes/static-social'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CreativeRouteImport } from './routes/creative'
import { Route as IndexRouteImport } from './routes/index'

const ThoughtLeadershipRoute = ThoughtLeadershipRouteImport.update({
  id: '/thought-leadership',
  path: '/thought-leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticSocialRoute = StaticSocialRouteImport.update({
  id: '/static-social',
  path: '/static-social',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativeRoute = CreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/creative': typeof CreativeRoute
  '/history': typeof HistoryRoute
  '/static-social': typeof StaticSocialRoute
  '/thought-leadership': typeof ThoughtLeadershipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/creative': typeof CreativeRoute
  '/history': typeof HistoryRoute
  '/static-social': typeof StaticSocialRoute
  '/thought-leadership': typeof ThoughtLeadershipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/creative': typeof CreativeRoute
  '/history': typeof HistoryRoute
  '/static-social': typeof StaticSocialRoute
  '/thought-leadership': typeof ThoughtLeadershipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/creative'
    | '/history'
    | '/static-social'
    | '/thought-leadership'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/creative' | '/history' | '/static-social' | '/thought-leadership'
  id:
    | '__root__'
    | '/'
    | '/creative'
    | '/history'
    | '/static-social'
    | '/thought-leadership'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreativeRoute: typeof CreativeRoute
  HistoryRoute: typeof HistoryRoute
  StaticSocialRoute: typeof StaticSocialRoute
  ThoughtLeadershipRoute: typeof ThoughtLeadershipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thought-leadership': {
      id: '/thought-leadership'
      path: '/thought-leadership'
      fullPath: '/thought-leadership'
      preLoaderRoute: typeof ThoughtLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/static-social': {
      id: '/static-social'
      path: '/static-social'
      fullPath: '/static-social'
      preLoaderRoute: typeof StaticSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative': {
      id: '/creative'
      path: '/creative'
      fullPath: '/creative'
      preLoaderRoute: typeof CreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreativeRoute: CreativeRoute,
  HistoryRoute: HistoryRoute,
  StaticSocialRoute: StaticSocialRoute,
  ThoughtLeadershipRoute: ThoughtLeadershipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
